/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 
7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?*/

// method works but is slow, try to optimize the isPrime part, maybe get a sieve and just iterate through it once
// but then we need to heuristically determine which prime to go up to
#include <stdio.h>

int sqrt(int);
int triangle(int);
int isPrime(int);

int main(void){
	printf("First triangular number with over 500 divisors: %d", triangle(500));
	return 0;
}

int sqrt(int num){
	/* returns integer sqrt of number for use in finding factors*/
	int i = 1;
	while (i*i < num){
		i += 1;
	}
	return i;
}

int isPrime(int num){
	for (int i=2;i<sqrt(num);i++){
		if (num % i == 0){
			return 0;
		}
	}
	return 1;
}

int triangle(int numDivisors){
	int triangle = 0;
	int integer = 1;
	int count = 1;
	while (count <= 500){
		count = 1;
		triangle += integer;
		printf("triangular num: %d\n", triangle);
		integer++;
		int temp = triangle;
		int i = 1;
		while (temp > 1){
			i++;
			if (isPrime(i)){
				int a = 0;
				while (temp % i == 0){
					temp = temp/i;
					a++;
				}
				count *= a+1;
			}
		}
	}
	return triangle;
}

