'''Consider all integer combinations of ab for 2 <= a <= 5 and 2 <= b <= 5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence 
of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 <= a <= 100 and 2 <= b <= 100?'''

# can just do a combinatorics algorithm - find the total number of possibilities
# and subtract the repeated ones
# total should be 99 * 99 then figure out what to eliminate
# first thing to notice is that we can reduce a^b repeats if b is divisible by some number c and a^c <= 100
# if so, then we eliminate c^(b/c) from the list because it is not distinct

# create a dictionary of key=base, value=exponent structure

maximum = 100

total = []

for a in range(2, maximum+1):
	for b in range(2, maximum+1):
		total.append(a**b)
print len(set(total))

