/*
Stated problem:
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

Subproblems:
Generate triangular numbers starting from T286.
Check if each of these numbers is pentagonal and hexagonal.
*/

var triangular = function(num){
	return num*(num+1)/2;
}

function checkPentagonal(num){
	num *= 2;
	for (var i=2;i<=Math.sqrt(num);i++){
		if (num % i == 0){
			var factor = num/i;
			if (factor == 3*i - 1){
				return true;
			}
		}
	}
	return false;
}

function checkHexagonal(num){
	for (var i=2;i<=Math.sqrt(num);i++){
		if (num % i == 0){
			var factor = num/i;
			if (factor == 2*i - 1){
				return true;
			}
		}
	}
	return false;
}

function solve(start){
	var n = start;
	while (true){
		var triangle = triangular(n);
		if (checkPentagonal(triangle) && checkHexagonal(triangle)){
			return triangle;
		}
		n += 1;
	}
}

console.log(solve(286));